

# This file was *autogenerated* from the file solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_128 = Integer(128); _sage_const_64 = Integer(64); _sage_const_4012 = Integer(4012); _sage_const_200 = Integer(200); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_50 = Integer(50)
import os
os.environ['TERM'] = 'xterm-256color'
os.environ['TERMINFO'] = '/usr/share/terminfo'

load('prng.sage')

from tqdm import trange
from pwn import *
from sys import stderr

legalPossibleMoves = [b'h2h4', b'f2f4', b'd2d4', b'b2b4']
moveToIndexMap = {legalPossibleMoves[idx][_sage_const_2 :_sage_const_4 ]: idx for idx in range(len(legalPossibleMoves))}

players = [
    "Magnus Carlsen", "Hikaru Nakamura", "Garry Kasparov", "Bobby Fischer",
    "Viswanathan Anand", "Vladimir Kramnik", "Fabiano Caruana", "Ding Liren",
    "Ian Nepomniachtchi", "Anatoly Karpov", "Mikhail Tal", "Alexander Alekhine",
    "Jose Raul Capablanca", "Paul Morphy", "Judith Polgar", "Wesley So",
    "Levon Aronian", "Maxime Vachier-Lagrave", "Sergey Karjakin", "Shakhriyar Mamedyarov",
    "Teimour Radjabov", "Boris Spassky", "Tigran Petrosian", "Veselin Topalov",
    "Peter Svidler", "Anish Giri", "Richard Rapport", "Jan-Krzysztof Duda",
    "Viktor Korchnoi", "Bent Larsen", "David Bronstein", "Samuel Reshevsky",
    "Efim Geller", "Mikhail Botvinnik", "Alexander Grischuk", "Vassily Ivanchuk",
    "Nigel Short", "Michael Adams", "Gata Kamsky", "Ruslan Ponomariov",
    "Vladimir Akopian", "Peter Leko", "Evgeny Bareev", "Alexei Shirov",
    "Vladimir Malakhov", "Boris Gelfand", "Vladimir Fedoseev", "Daniil Dubov",
    "Wei Yi", "Alireza Firouzja" , "Vladislav Artemiev", "Dmitry Andreikin", 
    "Radoslaw Wojtaszek", "Leinier Dominguez", "Pentala Harikrishna", "Sergey Movsesian",
    "Ernesto Inarkiev", "David Navara", "Vladislav Kovalev", "Jorden Van Foreest",
    "Nihal Sarin", "Vincent Keymer", "Awonder Liang", "Jeffery Xiong",
    "Praggnanandhaa Rameshbabu", "Raunak Sadhwani"
]

dim = _sage_const_128 
B = BooleanPolynomialRing(dim, 'b')
gens = B.gens()
s0 = vector(B, gens[:_sage_const_64 ])
s1 = vector(B, gens[_sage_const_64 :])
symbPrng = SymbXorShift128(s0, s1)
genMapping = {gens[idx]: idx for idx in range(len(gens))}


if args.REMOTE:
	conn = remote('chess.challs.srdnlen.it', _sage_const_4012 )
else:
	conn = process(['pypy3', 'main.py'], stderr = stderr)

leaks = []
relations = []
iterations = _sage_const_200 
# iterations = 5
for _ in trange(iterations):
	conn.sendlineafter(b'): ', b'1\nl')
	conn.recvuntil(b'\n\n1. ')
	move = conn.recvline().split(b' ')[_sage_const_0 ]
	idx = moveToIndexMap[move]
	bit = idx & _sage_const_1 
	leaks.append(bit)

	poly = symbPrng.bit()
	rel = [_sage_const_0 ] * dim
	for elem in poly.monomials():
		rel[genMapping[elem]] = _sage_const_1 
	
	relations.append(rel)

	for _ in range(_sage_const_3 ):
		symbPrng.skip()
	# print(f'{move = }, {moveToIndexMap[move] = }')

K = GF(_sage_const_2 )
M = Matrix(K, relations)
b = vector(K, leaks)

S = M.solve_right(b)
binrep = ''.join(map(str, S))
print(f'{binrep = }')
state0 = int(binrep[:_sage_const_64 ][::-_sage_const_1 ], _sage_const_2 )
state1 = int(binrep[_sage_const_64 :][::-_sage_const_1 ], _sage_const_2 )
print(f'{state0 = }, {state1 = }')

prng = XorShift128(state0, state1)
for _ in range(iterations * _sage_const_4 ):
	prng.next()

conn.sendline(b'3')
triviaSize = _sage_const_50 
for _ in trange(triviaSize):
	player = prng.choice(players)
	conn.sendlineafter(b'of?\n', player.encode())

conn.interactive()

